/* automatically generated by rust-bindgen 0.63.0 */

pub const TWON_PROTOCOLMINOR: u32 = 9;
pub const TWON_PROTOCOLMAJOR: u32 = 1;
pub const TWON_ARRAY: u32 = 3;
pub const TWON_ENUMERATION: u32 = 4;
pub const TWON_ONEVALUE: u32 = 5;
pub const TWON_RANGE: u32 = 6;
pub const TWON_ICONID: u32 = 962;
pub const TWON_DSMID: u32 = 461;
pub const TWON_DSMCODEID: u32 = 63;
pub const TWON_DONTCARE8: u32 = 255;
pub const TWON_DONTCARE16: u32 = 65535;
pub const TWON_DONTCARE32: u32 = 4294967295;
pub const TWMF_APPOWNS: u32 = 1;
pub const TWMF_DSMOWNS: u32 = 2;
pub const TWMF_DSOWNS: u32 = 4;
pub const TWMF_POINTER: u32 = 8;
pub const TWMF_HANDLE: u32 = 16;
pub const TWPA_RGB: u32 = 0;
pub const TWPA_GRAY: u32 = 1;
pub const TWPA_CMY: u32 = 2;
pub const TWTY_INT8: u32 = 0;
pub const TWTY_INT16: u32 = 1;
pub const TWTY_INT32: u32 = 2;
pub const TWTY_UINT8: u32 = 3;
pub const TWTY_UINT16: u32 = 4;
pub const TWTY_UINT32: u32 = 5;
pub const TWTY_BOOL: u32 = 6;
pub const TWTY_FIX32: u32 = 7;
pub const TWTY_FRAME: u32 = 8;
pub const TWTY_STR32: u32 = 9;
pub const TWTY_STR64: u32 = 10;
pub const TWTY_STR128: u32 = 11;
pub const TWTY_STR255: u32 = 12;
pub const TWTY_STR1024: u32 = 13;
pub const TWTY_UNI512: u32 = 14;
pub const TWBO_LSBFIRST: u32 = 0;
pub const TWBO_MSBFIRST: u32 = 1;
pub const TWCP_NONE: u32 = 0;
pub const TWCP_PACKBITS: u32 = 1;
pub const TWCP_GROUP31D: u32 = 2;
pub const TWCP_GROUP31DEOL: u32 = 3;
pub const TWCP_GROUP32D: u32 = 4;
pub const TWCP_GROUP4: u32 = 5;
pub const TWCP_JPEG: u32 = 6;
pub const TWCP_LZW: u32 = 7;
pub const TWCP_JBIG: u32 = 8;
pub const TWCP_PNG: u32 = 9;
pub const TWCP_RLE4: u32 = 10;
pub const TWCP_RLE8: u32 = 11;
pub const TWCP_BITFIELDS: u32 = 12;
pub const TWFF_TIFF: u32 = 0;
pub const TWFF_PICT: u32 = 1;
pub const TWFF_BMP: u32 = 2;
pub const TWFF_XBM: u32 = 3;
pub const TWFF_JFIF: u32 = 4;
pub const TWFF_FPX: u32 = 5;
pub const TWFF_TIFFMULTI: u32 = 6;
pub const TWFF_PNG: u32 = 7;
pub const TWFF_SPIFF: u32 = 8;
pub const TWFF_EXIF: u32 = 9;
pub const TWFT_RED: u32 = 0;
pub const TWFT_GREEN: u32 = 1;
pub const TWFT_BLUE: u32 = 2;
pub const TWFT_NONE: u32 = 3;
pub const TWFT_WHITE: u32 = 4;
pub const TWFT_CYAN: u32 = 5;
pub const TWFT_MAGENTA: u32 = 6;
pub const TWFT_YELLOW: u32 = 7;
pub const TWFT_BLACK: u32 = 8;
pub const TWLP_REFLECTIVE: u32 = 0;
pub const TWLP_TRANSMISSIVE: u32 = 1;
pub const TWLS_RED: u32 = 0;
pub const TWLS_GREEN: u32 = 1;
pub const TWLS_BLUE: u32 = 2;
pub const TWLS_NONE: u32 = 3;
pub const TWLS_WHITE: u32 = 4;
pub const TWLS_UV: u32 = 5;
pub const TWLS_IR: u32 = 6;
pub const TWOR_ROT0: u32 = 0;
pub const TWOR_ROT90: u32 = 1;
pub const TWOR_ROT180: u32 = 2;
pub const TWOR_ROT270: u32 = 3;
pub const TWOR_PORTRAIT: u32 = 0;
pub const TWOR_LANDSCAPE: u32 = 3;
pub const TWPC_CHUNKY: u32 = 0;
pub const TWPC_PLANAR: u32 = 1;
pub const TWPF_CHOCOLATE: u32 = 0;
pub const TWPF_VANILLA: u32 = 1;
pub const TWPT_BW: u32 = 0;
pub const TWPT_GRAY: u32 = 1;
pub const TWPT_RGB: u32 = 2;
pub const TWPT_PALETTE: u32 = 3;
pub const TWPT_CMY: u32 = 4;
pub const TWPT_CMYK: u32 = 5;
pub const TWPT_YUV: u32 = 6;
pub const TWPT_YUVK: u32 = 7;
pub const TWPT_CIEXYZ: u32 = 8;
pub const TWSS_NONE: u32 = 0;
pub const TWSS_A4LETTER: u32 = 1;
pub const TWSS_B5LETTER: u32 = 2;
pub const TWSS_USLETTER: u32 = 3;
pub const TWSS_USLEGAL: u32 = 4;
pub const TWSS_A5: u32 = 5;
pub const TWSS_B4: u32 = 6;
pub const TWSS_B6: u32 = 7;
pub const TWSS_USLEDGER: u32 = 9;
pub const TWSS_USEXECUTIVE: u32 = 10;
pub const TWSS_A3: u32 = 11;
pub const TWSS_B3: u32 = 12;
pub const TWSS_A6: u32 = 13;
pub const TWSS_C4: u32 = 14;
pub const TWSS_C5: u32 = 15;
pub const TWSS_C6: u32 = 16;
pub const TWSS_4A0: u32 = 17;
pub const TWSS_2A0: u32 = 18;
pub const TWSS_A0: u32 = 19;
pub const TWSS_A1: u32 = 20;
pub const TWSS_A2: u32 = 21;
pub const TWSS_A4: u32 = 1;
pub const TWSS_A7: u32 = 22;
pub const TWSS_A8: u32 = 23;
pub const TWSS_A9: u32 = 24;
pub const TWSS_A10: u32 = 25;
pub const TWSS_ISOB0: u32 = 26;
pub const TWSS_ISOB1: u32 = 27;
pub const TWSS_ISOB2: u32 = 28;
pub const TWSS_ISOB3: u32 = 12;
pub const TWSS_ISOB4: u32 = 6;
pub const TWSS_ISOB5: u32 = 29;
pub const TWSS_ISOB6: u32 = 7;
pub const TWSS_ISOB7: u32 = 30;
pub const TWSS_ISOB8: u32 = 31;
pub const TWSS_ISOB9: u32 = 32;
pub const TWSS_ISOB10: u32 = 33;
pub const TWSS_JISB0: u32 = 34;
pub const TWSS_JISB1: u32 = 35;
pub const TWSS_JISB2: u32 = 36;
pub const TWSS_JISB3: u32 = 37;
pub const TWSS_JISB4: u32 = 38;
pub const TWSS_JISB5: u32 = 2;
pub const TWSS_JISB6: u32 = 39;
pub const TWSS_JISB7: u32 = 40;
pub const TWSS_JISB8: u32 = 41;
pub const TWSS_JISB9: u32 = 42;
pub const TWSS_JISB10: u32 = 43;
pub const TWSS_C0: u32 = 44;
pub const TWSS_C1: u32 = 45;
pub const TWSS_C2: u32 = 46;
pub const TWSS_C3: u32 = 47;
pub const TWSS_C7: u32 = 48;
pub const TWSS_C8: u32 = 49;
pub const TWSS_C9: u32 = 50;
pub const TWSS_C10: u32 = 51;
pub const TWSS_USSTATEMENT: u32 = 52;
pub const TWSS_BUSINESSCARD: u32 = 53;
pub const TWSX_NATIVE: u32 = 0;
pub const TWSX_FILE: u32 = 1;
pub const TWSX_MEMORY: u32 = 2;
pub const TWSX_FILE2: u32 = 3;
pub const TWUN_INCHES: u32 = 0;
pub const TWUN_CENTIMETERS: u32 = 1;
pub const TWUN_PICAS: u32 = 2;
pub const TWUN_POINTS: u32 = 3;
pub const TWUN_TWIPS: u32 = 4;
pub const TWUN_PIXELS: u32 = 5;
pub const TWBR_THRESHOLD: u32 = 0;
pub const TWBR_HALFTONE: u32 = 1;
pub const TWBR_CUSTHALFTONE: u32 = 2;
pub const TWBR_DIFFUSION: u32 = 3;
pub const TWDX_NONE: u32 = 0;
pub const TWDX_1PASSDUPLEX: u32 = 1;
pub const TWDX_2PASSDUPLEX: u32 = 2;
pub const TWBT_3OF9: u32 = 0;
pub const TWBT_2OF5INTERLEAVED: u32 = 1;
pub const TWBT_2OF5NONINTERLEAVED: u32 = 2;
pub const TWBT_CODE93: u32 = 3;
pub const TWBT_CODE128: u32 = 4;
pub const TWBT_UCC128: u32 = 5;
pub const TWBT_CODABAR: u32 = 6;
pub const TWBT_UPCA: u32 = 7;
pub const TWBT_UPCE: u32 = 8;
pub const TWBT_EAN8: u32 = 9;
pub const TWBT_EAN13: u32 = 10;
pub const TWBT_POSTNET: u32 = 11;
pub const TWBT_PDF417: u32 = 12;
pub const TWBT_2OF5INDUSTRIAL: u32 = 13;
pub const TWBT_2OF5MATRIX: u32 = 14;
pub const TWBT_2OF5DATALOGIC: u32 = 15;
pub const TWBT_2OF5IATA: u32 = 16;
pub const TWBT_3OF9FULLASCII: u32 = 17;
pub const TWBT_CODABARWITHSTARTSTOP: u32 = 18;
pub const TWBT_MAXICODE: u32 = 19;
pub const TWDSK_SUCCESS: u32 = 0;
pub const TWDSK_REPORTONLY: u32 = 1;
pub const TWDSK_FAIL: u32 = 2;
pub const TWDSK_DISABLED: u32 = 3;
pub const TWPCH_PATCH1: u32 = 0;
pub const TWPCH_PATCH2: u32 = 1;
pub const TWPCH_PATCH3: u32 = 2;
pub const TWPCH_PATCH4: u32 = 3;
pub const TWPCH_PATCH6: u32 = 4;
pub const TWPCH_PATCHT: u32 = 5;
pub const TWJC_NONE: u32 = 0;
pub const TWJC_JSIC: u32 = 1;
pub const TWJC_JSIS: u32 = 2;
pub const TWJC_JSXC: u32 = 3;
pub const TWJC_JSXS: u32 = 4;
pub const TWBCOR_ROT0: u32 = 0;
pub const TWBCOR_ROT90: u32 = 1;
pub const TWBCOR_ROT180: u32 = 2;
pub const TWBCOR_ROT270: u32 = 3;
pub const TWBCOR_ROTX: u32 = 4;
pub const TWAF_WAV: u32 = 0;
pub const TWAF_AIFF: u32 = 1;
pub const TWAF_AU: u32 = 3;
pub const TWAF_SND: u32 = 4;
pub const TWAL_ALARM: u32 = 0;
pub const TWAL_FEEDERERROR: u32 = 1;
pub const TWAL_FEEDERWARNING: u32 = 2;
pub const TWAL_BARCODE: u32 = 3;
pub const TWAL_DOUBLEFEED: u32 = 4;
pub const TWAL_JAM: u32 = 5;
pub const TWAL_PATCHCODE: u32 = 6;
pub const TWAL_POWER: u32 = 7;
pub const TWAL_SKEW: u32 = 8;
pub const TWCB_AUTO: u32 = 0;
pub const TWCB_CLEAR: u32 = 1;
pub const TWCB_NOCLEAR: u32 = 2;
pub const TWDE_CUSTOMEVENTS: u32 = 32768;
pub const TWDE_CHECKAUTOMATICCAPTURE: u32 = 0;
pub const TWDE_CHECKBATTERY: u32 = 1;
pub const TWDE_CHECKDEVICEONLINE: u32 = 2;
pub const TWDE_CHECKFLASH: u32 = 3;
pub const TWDE_CHECKPOWERSUPPLY: u32 = 4;
pub const TWDE_CHECKRESOLUTION: u32 = 5;
pub const TWDE_DEVICEADDED: u32 = 6;
pub const TWDE_DEVICEOFFLINE: u32 = 7;
pub const TWDE_DEVICEREADY: u32 = 8;
pub const TWDE_DEVICEREMOVED: u32 = 9;
pub const TWDE_IMAGECAPTURED: u32 = 10;
pub const TWDE_IMAGEDELETED: u32 = 11;
pub const TWDE_PAPERDOUBLEFEED: u32 = 12;
pub const TWDE_PAPERJAM: u32 = 13;
pub const TWDE_LAMPFAILURE: u32 = 14;
pub const TWDE_POWERSAVE: u32 = 15;
pub const TWDE_POWERSAVENOTIFY: u32 = 16;
pub const TWFA_NONE: u32 = 0;
pub const TWFA_LEFT: u32 = 1;
pub const TWFA_CENTER: u32 = 2;
pub const TWFA_RIGHT: u32 = 3;
pub const TWFO_FIRSTPAGEFIRST: u32 = 0;
pub const TWFO_LASTPAGEFIRST: u32 = 1;
pub const TWFS_FILESYSTEM: u32 = 0;
pub const TWFS_RECURSIVEDELETE: u32 = 1;
pub const TWPS_EXTERNAL: u32 = 0;
pub const TWPS_BATTERY: u32 = 1;
pub const TWPR_IMPRINTERTOPBEFORE: u32 = 0;
pub const TWPR_IMPRINTERTOPAFTER: u32 = 1;
pub const TWPR_IMPRINTERBOTTOMBEFORE: u32 = 2;
pub const TWPR_IMPRINTERBOTTOMAFTER: u32 = 3;
pub const TWPR_ENDORSERTOPBEFORE: u32 = 4;
pub const TWPR_ENDORSERTOPAFTER: u32 = 5;
pub const TWPR_ENDORSERBOTTOMBEFORE: u32 = 6;
pub const TWPR_ENDORSERBOTTOMAFTER: u32 = 7;
pub const TWPM_SINGLESTRING: u32 = 0;
pub const TWPM_MULTISTRING: u32 = 1;
pub const TWPM_COMPOUNDSTRING: u32 = 2;
pub const TWBD_HORZ: u32 = 0;
pub const TWBD_VERT: u32 = 1;
pub const TWBD_HORZVERT: u32 = 2;
pub const TWBD_VERTHORZ: u32 = 3;
pub const TWFL_NONE: u32 = 0;
pub const TWFL_OFF: u32 = 1;
pub const TWFL_ON: u32 = 2;
pub const TWFL_AUTO: u32 = 3;
pub const TWFL_REDEYE: u32 = 4;
pub const TWFR_BOOK: u32 = 0;
pub const TWFR_FANFOLD: u32 = 1;
pub const TWIF_NONE: u32 = 0;
pub const TWIF_AUTO: u32 = 1;
pub const TWIF_LOWPASS: u32 = 2;
pub const TWIF_BANDPASS: u32 = 3;
pub const TWIF_HIGHPASS: u32 = 4;
pub const TWIF_TEXT: u32 = 3;
pub const TWIF_FINELINE: u32 = 4;
pub const TWNF_NONE: u32 = 0;
pub const TWNF_AUTO: u32 = 1;
pub const TWNF_LONEPIXEL: u32 = 2;
pub const TWNF_MAJORITYRULE: u32 = 3;
pub const TWOV_NONE: u32 = 0;
pub const TWOV_AUTO: u32 = 1;
pub const TWOV_TOPBOTTOM: u32 = 2;
pub const TWOV_LEFTRIGHT: u32 = 3;
pub const TWOV_ALL: u32 = 4;
pub const TWFY_CAMERA: u32 = 0;
pub const TWFY_CAMERATOP: u32 = 1;
pub const TWFY_CAMERABOTTOM: u32 = 2;
pub const TWFY_CAMERAPREVIEW: u32 = 3;
pub const TWFY_DOMAIN: u32 = 4;
pub const TWFY_HOST: u32 = 5;
pub const TWFY_DIRECTORY: u32 = 6;
pub const TWFY_IMAGE: u32 = 7;
pub const TWFY_UNKNOWN: u32 = 8;
pub const TWJQ_UNKNOWN: i32 = -4;
pub const TWJQ_LOW: i32 = -3;
pub const TWJQ_MEDIUM: i32 = -2;
pub const TWJQ_HIGH: i32 = -1;
pub const TWCY_AFGHANISTAN: u32 = 1001;
pub const TWCY_ALGERIA: u32 = 213;
pub const TWCY_AMERICANSAMOA: u32 = 684;
pub const TWCY_ANDORRA: u32 = 27;
pub const TWCY_ANGOLA: u32 = 1002;
pub const TWCY_ANGUILLA: u32 = 8090;
pub const TWCY_ANTIGUA: u32 = 8091;
pub const TWCY_ARGENTINA: u32 = 54;
pub const TWCY_ARUBA: u32 = 297;
pub const TWCY_ASCENSIONI: u32 = 247;
pub const TWCY_AUSTRALIA: u32 = 61;
pub const TWCY_AUSTRIA: u32 = 43;
pub const TWCY_BAHAMAS: u32 = 8092;
pub const TWCY_BAHRAIN: u32 = 973;
pub const TWCY_BANGLADESH: u32 = 880;
pub const TWCY_BARBADOS: u32 = 8093;
pub const TWCY_BELGIUM: u32 = 32;
pub const TWCY_BELIZE: u32 = 501;
pub const TWCY_BENIN: u32 = 229;
pub const TWCY_BERMUDA: u32 = 8094;
pub const TWCY_BHUTAN: u32 = 1003;
pub const TWCY_BOLIVIA: u32 = 591;
pub const TWCY_BOTSWANA: u32 = 267;
pub const TWCY_BRITAIN: u32 = 6;
pub const TWCY_BRITVIRGINIS: u32 = 8095;
pub const TWCY_BRAZIL: u32 = 55;
pub const TWCY_BRUNEI: u32 = 673;
pub const TWCY_BULGARIA: u32 = 359;
pub const TWCY_BURKINAFASO: u32 = 1004;
pub const TWCY_BURMA: u32 = 1005;
pub const TWCY_BURUNDI: u32 = 1006;
pub const TWCY_CAMAROON: u32 = 237;
pub const TWCY_CANADA: u32 = 2;
pub const TWCY_CAPEVERDEIS: u32 = 238;
pub const TWCY_CAYMANIS: u32 = 8096;
pub const TWCY_CENTRALAFREP: u32 = 1007;
pub const TWCY_CHAD: u32 = 1008;
pub const TWCY_CHILE: u32 = 56;
pub const TWCY_CHINA: u32 = 86;
pub const TWCY_CHRISTMASIS: u32 = 1009;
pub const TWCY_COCOSIS: u32 = 1009;
pub const TWCY_COLOMBIA: u32 = 57;
pub const TWCY_COMOROS: u32 = 1010;
pub const TWCY_CONGO: u32 = 1011;
pub const TWCY_COOKIS: u32 = 1012;
pub const TWCY_COSTARICA: u32 = 506;
pub const TWCY_CUBA: u32 = 5;
pub const TWCY_CYPRUS: u32 = 357;
pub const TWCY_CZECHOSLOVAKIA: u32 = 42;
pub const TWCY_DENMARK: u32 = 45;
pub const TWCY_DJIBOUTI: u32 = 1013;
pub const TWCY_DOMINICA: u32 = 8097;
pub const TWCY_DOMINCANREP: u32 = 8098;
pub const TWCY_EASTERIS: u32 = 1014;
pub const TWCY_ECUADOR: u32 = 593;
pub const TWCY_EGYPT: u32 = 20;
pub const TWCY_ELSALVADOR: u32 = 503;
pub const TWCY_EQGUINEA: u32 = 1015;
pub const TWCY_ETHIOPIA: u32 = 251;
pub const TWCY_FALKLANDIS: u32 = 1016;
pub const TWCY_FAEROEIS: u32 = 298;
pub const TWCY_FIJIISLANDS: u32 = 679;
pub const TWCY_FINLAND: u32 = 358;
pub const TWCY_FRANCE: u32 = 33;
pub const TWCY_FRANTILLES: u32 = 596;
pub const TWCY_FRGUIANA: u32 = 594;
pub const TWCY_FRPOLYNEISA: u32 = 689;
pub const TWCY_FUTANAIS: u32 = 1043;
pub const TWCY_GABON: u32 = 241;
pub const TWCY_GAMBIA: u32 = 220;
pub const TWCY_GERMANY: u32 = 49;
pub const TWCY_GHANA: u32 = 233;
pub const TWCY_GIBRALTER: u32 = 350;
pub const TWCY_GREECE: u32 = 30;
pub const TWCY_GREENLAND: u32 = 299;
pub const TWCY_GRENADA: u32 = 8099;
pub const TWCY_GRENEDINES: u32 = 8015;
pub const TWCY_GUADELOUPE: u32 = 590;
pub const TWCY_GUAM: u32 = 671;
pub const TWCY_GUANTANAMOBAY: u32 = 5399;
pub const TWCY_GUATEMALA: u32 = 502;
pub const TWCY_GUINEA: u32 = 224;
pub const TWCY_GUINEABISSAU: u32 = 1017;
pub const TWCY_GUYANA: u32 = 592;
pub const TWCY_HAITI: u32 = 509;
pub const TWCY_HONDURAS: u32 = 504;
pub const TWCY_HONGKONG: u32 = 852;
pub const TWCY_HUNGARY: u32 = 36;
pub const TWCY_ICELAND: u32 = 354;
pub const TWCY_INDIA: u32 = 91;
pub const TWCY_INDONESIA: u32 = 62;
pub const TWCY_IRAN: u32 = 98;
pub const TWCY_IRAQ: u32 = 964;
pub const TWCY_IRELAND: u32 = 353;
pub const TWCY_ISRAEL: u32 = 972;
pub const TWCY_ITALY: u32 = 39;
pub const TWCY_IVORYCOAST: u32 = 225;
pub const TWCY_JAMAICA: u32 = 8010;
pub const TWCY_JAPAN: u32 = 81;
pub const TWCY_JORDAN: u32 = 962;
pub const TWCY_KENYA: u32 = 254;
pub const TWCY_KIRIBATI: u32 = 1018;
pub const TWCY_KOREA: u32 = 82;
pub const TWCY_KUWAIT: u32 = 965;
pub const TWCY_LAOS: u32 = 1019;
pub const TWCY_LEBANON: u32 = 1020;
pub const TWCY_LIBERIA: u32 = 231;
pub const TWCY_LIBYA: u32 = 218;
pub const TWCY_LIECHTENSTEIN: u32 = 41;
pub const TWCY_LUXENBOURG: u32 = 352;
pub const TWCY_MACAO: u32 = 853;
pub const TWCY_MADAGASCAR: u32 = 1021;
pub const TWCY_MALAWI: u32 = 265;
pub const TWCY_MALAYSIA: u32 = 60;
pub const TWCY_MALDIVES: u32 = 960;
pub const TWCY_MALI: u32 = 1022;
pub const TWCY_MALTA: u32 = 356;
pub const TWCY_MARSHALLIS: u32 = 692;
pub const TWCY_MAURITANIA: u32 = 1023;
pub const TWCY_MAURITIUS: u32 = 230;
pub const TWCY_MEXICO: u32 = 3;
pub const TWCY_MICRONESIA: u32 = 691;
pub const TWCY_MIQUELON: u32 = 508;
pub const TWCY_MONACO: u32 = 33;
pub const TWCY_MONGOLIA: u32 = 1024;
pub const TWCY_MONTSERRAT: u32 = 8011;
pub const TWCY_MOROCCO: u32 = 212;
pub const TWCY_MOZAMBIQUE: u32 = 1025;
pub const TWCY_NAMIBIA: u32 = 264;
pub const TWCY_NAURU: u32 = 1026;
pub const TWCY_NEPAL: u32 = 977;
pub const TWCY_NETHERLANDS: u32 = 31;
pub const TWCY_NETHANTILLES: u32 = 599;
pub const TWCY_NEVIS: u32 = 8012;
pub const TWCY_NEWCALEDONIA: u32 = 687;
pub const TWCY_NEWZEALAND: u32 = 64;
pub const TWCY_NICARAGUA: u32 = 505;
pub const TWCY_NIGER: u32 = 227;
pub const TWCY_NIGERIA: u32 = 234;
pub const TWCY_NIUE: u32 = 1027;
pub const TWCY_NORFOLKI: u32 = 1028;
pub const TWCY_NORWAY: u32 = 47;
pub const TWCY_OMAN: u32 = 968;
pub const TWCY_PAKISTAN: u32 = 92;
pub const TWCY_PALAU: u32 = 1029;
pub const TWCY_PANAMA: u32 = 507;
pub const TWCY_PARAGUAY: u32 = 595;
pub const TWCY_PERU: u32 = 51;
pub const TWCY_PHILLIPPINES: u32 = 63;
pub const TWCY_PITCAIRNIS: u32 = 1030;
pub const TWCY_PNEWGUINEA: u32 = 675;
pub const TWCY_POLAND: u32 = 48;
pub const TWCY_PORTUGAL: u32 = 351;
pub const TWCY_QATAR: u32 = 974;
pub const TWCY_REUNIONI: u32 = 1031;
pub const TWCY_ROMANIA: u32 = 40;
pub const TWCY_RWANDA: u32 = 250;
pub const TWCY_SAIPAN: u32 = 670;
pub const TWCY_SANMARINO: u32 = 39;
pub const TWCY_SAOTOME: u32 = 1033;
pub const TWCY_SAUDIARABIA: u32 = 966;
pub const TWCY_SENEGAL: u32 = 221;
pub const TWCY_SEYCHELLESIS: u32 = 1034;
pub const TWCY_SIERRALEONE: u32 = 1035;
pub const TWCY_SINGAPORE: u32 = 65;
pub const TWCY_SOLOMONIS: u32 = 1036;
pub const TWCY_SOMALI: u32 = 1037;
pub const TWCY_SOUTHAFRICA: u32 = 27;
pub const TWCY_SPAIN: u32 = 34;
pub const TWCY_SRILANKA: u32 = 94;
pub const TWCY_STHELENA: u32 = 1032;
pub const TWCY_STKITTS: u32 = 8013;
pub const TWCY_STLUCIA: u32 = 8014;
pub const TWCY_STPIERRE: u32 = 508;
pub const TWCY_STVINCENT: u32 = 8015;
pub const TWCY_SUDAN: u32 = 1038;
pub const TWCY_SURINAME: u32 = 597;
pub const TWCY_SWAZILAND: u32 = 268;
pub const TWCY_SWEDEN: u32 = 46;
pub const TWCY_SWITZERLAND: u32 = 41;
pub const TWCY_SYRIA: u32 = 1039;
pub const TWCY_TAIWAN: u32 = 886;
pub const TWCY_TANZANIA: u32 = 255;
pub const TWCY_THAILAND: u32 = 66;
pub const TWCY_TOBAGO: u32 = 8016;
pub const TWCY_TOGO: u32 = 228;
pub const TWCY_TONGAIS: u32 = 676;
pub const TWCY_TRINIDAD: u32 = 8016;
pub const TWCY_TUNISIA: u32 = 216;
pub const TWCY_TURKEY: u32 = 90;
pub const TWCY_TURKSCAICOS: u32 = 8017;
pub const TWCY_TUVALU: u32 = 1040;
pub const TWCY_UGANDA: u32 = 256;
pub const TWCY_USSR: u32 = 7;
pub const TWCY_UAEMIRATES: u32 = 971;
pub const TWCY_UNITEDKINGDOM: u32 = 44;
pub const TWCY_USA: u32 = 1;
pub const TWCY_URUGUAY: u32 = 598;
pub const TWCY_VANUATU: u32 = 1041;
pub const TWCY_VATICANCITY: u32 = 39;
pub const TWCY_VENEZUELA: u32 = 58;
pub const TWCY_WAKE: u32 = 1042;
pub const TWCY_WALLISIS: u32 = 1043;
pub const TWCY_WESTERNSAHARA: u32 = 1044;
pub const TWCY_WESTERNSAMOA: u32 = 1045;
pub const TWCY_YEMEN: u32 = 1046;
pub const TWCY_YUGOSLAVIA: u32 = 38;
pub const TWCY_ZAIRE: u32 = 243;
pub const TWCY_ZAMBIA: u32 = 260;
pub const TWCY_ZIMBABWE: u32 = 263;
pub const TWCY_ALBANIA: u32 = 355;
pub const TWCY_ARMENIA: u32 = 374;
pub const TWCY_AZERBAIJAN: u32 = 994;
pub const TWCY_BELARUS: u32 = 375;
pub const TWCY_BOSNIAHERZGO: u32 = 387;
pub const TWCY_CAMBODIA: u32 = 855;
pub const TWCY_CROATIA: u32 = 385;
pub const TWCY_CZECHREPUBLIC: u32 = 420;
pub const TWCY_DIEGOGARCIA: u32 = 246;
pub const TWCY_ERITREA: u32 = 291;
pub const TWCY_ESTONIA: u32 = 372;
pub const TWCY_GEORGIA: u32 = 995;
pub const TWCY_LATVIA: u32 = 371;
pub const TWCY_LESOTHO: u32 = 266;
pub const TWCY_LITHUANIA: u32 = 370;
pub const TWCY_MACEDONIA: u32 = 389;
pub const TWCY_MAYOTTEIS: u32 = 269;
pub const TWCY_MOLDOVA: u32 = 373;
pub const TWCY_MYANMAR: u32 = 95;
pub const TWCY_NORTHKOREA: u32 = 850;
pub const TWCY_PUERTORICO: u32 = 787;
pub const TWCY_RUSSIA: u32 = 7;
pub const TWCY_SERBIA: u32 = 381;
pub const TWCY_SLOVAKIA: u32 = 421;
pub const TWCY_SLOVENIA: u32 = 386;
pub const TWCY_SOUTHKOREA: u32 = 82;
pub const TWCY_UKRAINE: u32 = 380;
pub const TWCY_USVIRGINIS: u32 = 340;
pub const TWCY_VIETNAM: u32 = 84;
pub const TWLG_DAN: u32 = 0;
pub const TWLG_DUT: u32 = 1;
pub const TWLG_ENG: u32 = 2;
pub const TWLG_FCF: u32 = 3;
pub const TWLG_FIN: u32 = 4;
pub const TWLG_FRN: u32 = 5;
pub const TWLG_GER: u32 = 6;
pub const TWLG_ICE: u32 = 7;
pub const TWLG_ITN: u32 = 8;
pub const TWLG_NOR: u32 = 9;
pub const TWLG_POR: u32 = 10;
pub const TWLG_SPA: u32 = 11;
pub const TWLG_SWE: u32 = 12;
pub const TWLG_USA: u32 = 13;
pub const TWLG_USERLOCALE: i32 = -1;
pub const TWLG_AFRIKAANS: u32 = 14;
pub const TWLG_ALBANIA: u32 = 15;
pub const TWLG_ARABIC: u32 = 16;
pub const TWLG_ARABIC_ALGERIA: u32 = 17;
pub const TWLG_ARABIC_BAHRAIN: u32 = 18;
pub const TWLG_ARABIC_EGYPT: u32 = 19;
pub const TWLG_ARABIC_IRAQ: u32 = 20;
pub const TWLG_ARABIC_JORDAN: u32 = 21;
pub const TWLG_ARABIC_KUWAIT: u32 = 22;
pub const TWLG_ARABIC_LEBANON: u32 = 23;
pub const TWLG_ARABIC_LIBYA: u32 = 24;
pub const TWLG_ARABIC_MOROCCO: u32 = 25;
pub const TWLG_ARABIC_OMAN: u32 = 26;
pub const TWLG_ARABIC_QATAR: u32 = 27;
pub const TWLG_ARABIC_SAUDIARABIA: u32 = 28;
pub const TWLG_ARABIC_SYRIA: u32 = 29;
pub const TWLG_ARABIC_TUNISIA: u32 = 30;
pub const TWLG_ARABIC_UAE: u32 = 31;
pub const TWLG_ARABIC_YEMEN: u32 = 32;
pub const TWLG_BASQUE: u32 = 33;
pub const TWLG_BYELORUSSIAN: u32 = 34;
pub const TWLG_BULGARIAN: u32 = 35;
pub const TWLG_CATALAN: u32 = 36;
pub const TWLG_CHINESE: u32 = 37;
pub const TWLG_CHINESE_HONGKONG: u32 = 38;
pub const TWLG_CHINESE_PRC: u32 = 39;
pub const TWLG_CHINESE_SINGAPORE: u32 = 40;
pub const TWLG_CHINESE_SIMPLIFIED: u32 = 41;
pub const TWLG_CHINESE_TAIWAN: u32 = 42;
pub const TWLG_CHINESE_TRADITIONAL: u32 = 43;
pub const TWLG_CROATIA: u32 = 44;
pub const TWLG_CZECH: u32 = 45;
pub const TWLG_DANISH: u32 = 0;
pub const TWLG_DUTCH: u32 = 1;
pub const TWLG_DUTCH_BELGIAN: u32 = 46;
pub const TWLG_ENGLISH: u32 = 2;
pub const TWLG_ENGLISH_AUSTRALIAN: u32 = 47;
pub const TWLG_ENGLISH_CANADIAN: u32 = 48;
pub const TWLG_ENGLISH_IRELAND: u32 = 49;
pub const TWLG_ENGLISH_NEWZEALAND: u32 = 50;
pub const TWLG_ENGLISH_SOUTHAFRICA: u32 = 51;
pub const TWLG_ENGLISH_UK: u32 = 52;
pub const TWLG_ENGLISH_USA: u32 = 13;
pub const TWLG_ESTONIAN: u32 = 53;
pub const TWLG_FAEROESE: u32 = 54;
pub const TWLG_FARSI: u32 = 55;
pub const TWLG_FINNISH: u32 = 4;
pub const TWLG_FRENCH: u32 = 5;
pub const TWLG_FRENCH_BELGIAN: u32 = 56;
pub const TWLG_FRENCH_CANADIAN: u32 = 3;
pub const TWLG_FRENCH_LUXEMBOURG: u32 = 57;
pub const TWLG_FRENCH_SWISS: u32 = 58;
pub const TWLG_GERMAN: u32 = 6;
pub const TWLG_GERMAN_AUSTRIAN: u32 = 59;
pub const TWLG_GERMAN_LUXEMBOURG: u32 = 60;
pub const TWLG_GERMAN_LIECHTENSTEIN: u32 = 61;
pub const TWLG_GERMAN_SWISS: u32 = 62;
pub const TWLG_GREEK: u32 = 63;
pub const TWLG_HEBREW: u32 = 64;
pub const TWLG_HUNGARIAN: u32 = 65;
pub const TWLG_ICELANDIC: u32 = 7;
pub const TWLG_INDONESIAN: u32 = 66;
pub const TWLG_ITALIAN: u32 = 8;
pub const TWLG_ITALIAN_SWISS: u32 = 67;
pub const TWLG_JAPANESE: u32 = 68;
pub const TWLG_KOREAN: u32 = 69;
pub const TWLG_KOREAN_JOHAB: u32 = 70;
pub const TWLG_LATVIAN: u32 = 71;
pub const TWLG_LITHUANIAN: u32 = 72;
pub const TWLG_NORWEGIAN: u32 = 9;
pub const TWLG_NORWEGIAN_BOKMAL: u32 = 73;
pub const TWLG_NORWEGIAN_NYNORSK: u32 = 74;
pub const TWLG_POLISH: u32 = 75;
pub const TWLG_PORTUGUESE: u32 = 10;
pub const TWLG_PORTUGUESE_BRAZIL: u32 = 76;
pub const TWLG_ROMANIAN: u32 = 77;
pub const TWLG_RUSSIAN: u32 = 78;
pub const TWLG_SERBIAN_LATIN: u32 = 79;
pub const TWLG_SLOVAK: u32 = 80;
pub const TWLG_SLOVENIAN: u32 = 81;
pub const TWLG_SPANISH: u32 = 11;
pub const TWLG_SPANISH_MEXICAN: u32 = 82;
pub const TWLG_SPANISH_MODERN: u32 = 83;
pub const TWLG_SWEDISH: u32 = 12;
pub const TWLG_THAI: u32 = 84;
pub const TWLG_TURKISH: u32 = 85;
pub const TWLG_UKRANIAN: u32 = 86;
pub const TWLG_ASSAMESE: u32 = 87;
pub const TWLG_BENGALI: u32 = 88;
pub const TWLG_BIHARI: u32 = 89;
pub const TWLG_BODO: u32 = 90;
pub const TWLG_DOGRI: u32 = 91;
pub const TWLG_GUJARATI: u32 = 92;
pub const TWLG_HARYANVI: u32 = 93;
pub const TWLG_HINDI: u32 = 94;
pub const TWLG_KANNADA: u32 = 95;
pub const TWLG_KASHMIRI: u32 = 96;
pub const TWLG_MALAYALAM: u32 = 97;
pub const TWLG_MARATHI: u32 = 98;
pub const TWLG_MARWARI: u32 = 99;
pub const TWLG_MEGHALAYAN: u32 = 100;
pub const TWLG_MIZO: u32 = 101;
pub const TWLG_NAGA: u32 = 102;
pub const TWLG_ORISSI: u32 = 103;
pub const TWLG_PUNJABI: u32 = 104;
pub const TWLG_PUSHTU: u32 = 105;
pub const TWLG_SERBIAN_CYRILLIC: u32 = 106;
pub const TWLG_SIKKIMI: u32 = 107;
pub const TWLG_SWEDISH_FINLAND: u32 = 108;
pub const TWLG_TAMIL: u32 = 109;
pub const TWLG_TELUGU: u32 = 110;
pub const TWLG_TRIPURI: u32 = 111;
pub const TWLG_URDU: u32 = 112;
pub const TWLG_VIETNAMESE: u32 = 113;
pub const DG_CONTROL: u32 = 1;
pub const DG_IMAGE: u32 = 2;
pub const DG_AUDIO: u32 = 4;
pub const DAT_NULL: u32 = 0;
pub const DAT_CUSTOMBASE: u32 = 32768;
pub const DAT_CAPABILITY: u32 = 1;
pub const DAT_EVENT: u32 = 2;
pub const DAT_IDENTITY: u32 = 3;
pub const DAT_PARENT: u32 = 4;
pub const DAT_PENDINGXFERS: u32 = 5;
pub const DAT_SETUPMEMXFER: u32 = 6;
pub const DAT_SETUPFILEXFER: u32 = 7;
pub const DAT_STATUS: u32 = 8;
pub const DAT_USERINTERFACE: u32 = 9;
pub const DAT_XFERGROUP: u32 = 10;
pub const DAT_TWUNKIDENTITY: u32 = 11;
pub const DAT_CUSTOMDSDATA: u32 = 12;
pub const DAT_DEVICEEVENT: u32 = 13;
pub const DAT_FILESYSTEM: u32 = 14;
pub const DAT_PASSTHRU: u32 = 15;
pub const DAT_CALLBACK: u32 = 16;
pub const DAT_IMAGEINFO: u32 = 257;
pub const DAT_IMAGELAYOUT: u32 = 258;
pub const DAT_IMAGEMEMXFER: u32 = 259;
pub const DAT_IMAGENATIVEXFER: u32 = 260;
pub const DAT_IMAGEFILEXFER: u32 = 261;
pub const DAT_CIECOLOR: u32 = 262;
pub const DAT_GRAYRESPONSE: u32 = 263;
pub const DAT_RGBRESPONSE: u32 = 264;
pub const DAT_JPEGCOMPRESSION: u32 = 265;
pub const DAT_PALETTE8: u32 = 266;
pub const DAT_EXTIMAGEINFO: u32 = 267;
pub const DAT_AUDIOFILEXFER: u32 = 513;
pub const DAT_AUDIOINFO: u32 = 514;
pub const DAT_AUDIONATIVEXFER: u32 = 515;
pub const DAT_SETUPFILEXFER2: u32 = 769;
pub const MSG_NULL: u32 = 0;
pub const MSG_CUSTOMBASE: u32 = 32768;
pub const MSG_GET: u32 = 1;
pub const MSG_GETCURRENT: u32 = 2;
pub const MSG_GETDEFAULT: u32 = 3;
pub const MSG_GETFIRST: u32 = 4;
pub const MSG_GETNEXT: u32 = 5;
pub const MSG_SET: u32 = 6;
pub const MSG_RESET: u32 = 7;
pub const MSG_QUERYSUPPORT: u32 = 8;
pub const MSG_XFERREADY: u32 = 257;
pub const MSG_CLOSEDSREQ: u32 = 258;
pub const MSG_CLOSEDSOK: u32 = 259;
pub const MSG_DEVICEEVENT: u32 = 260;
pub const MSG_CHECKSTATUS: u32 = 513;
pub const MSG_OPENDSM: u32 = 769;
pub const MSG_CLOSEDSM: u32 = 770;
pub const MSG_OPENDS: u32 = 1025;
pub const MSG_CLOSEDS: u32 = 1026;
pub const MSG_USERSELECT: u32 = 1027;
pub const MSG_DISABLEDS: u32 = 1281;
pub const MSG_ENABLEDS: u32 = 1282;
pub const MSG_ENABLEDSUIONLY: u32 = 1283;
pub const MSG_PROCESSEVENT: u32 = 1537;
pub const MSG_ENDXFER: u32 = 1793;
pub const MSG_STOPFEEDER: u32 = 1794;
pub const MSG_CHANGEDIRECTORY: u32 = 2049;
pub const MSG_CREATEDIRECTORY: u32 = 2050;
pub const MSG_DELETE: u32 = 2051;
pub const MSG_FORMATMEDIA: u32 = 2052;
pub const MSG_GETCLOSE: u32 = 2053;
pub const MSG_GETFIRSTFILE: u32 = 2054;
pub const MSG_GETINFO: u32 = 2055;
pub const MSG_GETNEXTFILE: u32 = 2056;
pub const MSG_RENAME: u32 = 2057;
pub const MSG_COPY: u32 = 2058;
pub const MSG_AUTOMATICCAPTUREDIRECTORY: u32 = 2059;
pub const MSG_PASSTHRU: u32 = 2305;
pub const MSG_REGISTER_CALLBACK: u32 = 2306;
pub const MSG_INVOKE_CALLBACK: u32 = 2307;
pub const CAP_CUSTOMBASE: u32 = 32768;
pub const CAP_XFERCOUNT: u32 = 1;
pub const ICAP_COMPRESSION: u32 = 256;
pub const ICAP_PIXELTYPE: u32 = 257;
pub const ICAP_UNITS: u32 = 258;
pub const ICAP_XFERMECH: u32 = 259;
pub const CAP_AUTHOR: u32 = 4096;
pub const CAP_CAPTION: u32 = 4097;
pub const CAP_FEEDERENABLED: u32 = 4098;
pub const CAP_FEEDERLOADED: u32 = 4099;
pub const CAP_TIMEDATE: u32 = 4100;
pub const CAP_SUPPORTEDCAPS: u32 = 4101;
pub const CAP_EXTENDEDCAPS: u32 = 4102;
pub const CAP_AUTOFEED: u32 = 4103;
pub const CAP_CLEARPAGE: u32 = 4104;
pub const CAP_FEEDPAGE: u32 = 4105;
pub const CAP_REWINDPAGE: u32 = 4106;
pub const CAP_INDICATORS: u32 = 4107;
pub const CAP_SUPPORTEDCAPSEXT: u32 = 4108;
pub const CAP_PAPERDETECTABLE: u32 = 4109;
pub const CAP_UICONTROLLABLE: u32 = 4110;
pub const CAP_DEVICEONLINE: u32 = 4111;
pub const CAP_AUTOSCAN: u32 = 4112;
pub const CAP_THUMBNAILSENABLED: u32 = 4113;
pub const CAP_DUPLEX: u32 = 4114;
pub const CAP_DUPLEXENABLED: u32 = 4115;
pub const CAP_ENABLEDSUIONLY: u32 = 4116;
pub const CAP_CUSTOMDSDATA: u32 = 4117;
pub const CAP_ENDORSER: u32 = 4118;
pub const CAP_JOBCONTROL: u32 = 4119;
pub const CAP_ALARMS: u32 = 4120;
pub const CAP_ALARMVOLUME: u32 = 4121;
pub const CAP_AUTOMATICCAPTURE: u32 = 4122;
pub const CAP_TIMEBEFOREFIRSTCAPTURE: u32 = 4123;
pub const CAP_TIMEBETWEENCAPTURES: u32 = 4124;
pub const CAP_CLEARBUFFERS: u32 = 4125;
pub const CAP_MAXBATCHBUFFERS: u32 = 4126;
pub const CAP_DEVICETIMEDATE: u32 = 4127;
pub const CAP_POWERSUPPLY: u32 = 4128;
pub const CAP_CAMERAPREVIEWUI: u32 = 4129;
pub const CAP_DEVICEEVENT: u32 = 4130;
pub const CAP_SERIALNUMBER: u32 = 4132;
pub const CAP_PRINTER: u32 = 4134;
pub const CAP_PRINTERENABLED: u32 = 4135;
pub const CAP_PRINTERINDEX: u32 = 4136;
pub const CAP_PRINTERMODE: u32 = 4137;
pub const CAP_PRINTERSTRING: u32 = 4138;
pub const CAP_PRINTERSUFFIX: u32 = 4139;
pub const CAP_LANGUAGE: u32 = 4140;
pub const CAP_FEEDERALIGNMENT: u32 = 4141;
pub const CAP_FEEDERORDER: u32 = 4142;
pub const CAP_REACQUIREALLOWED: u32 = 4144;
pub const CAP_BATTERYMINUTES: u32 = 4146;
pub const CAP_BATTERYPERCENTAGE: u32 = 4147;
pub const ICAP_AUTOBRIGHT: u32 = 4352;
pub const ICAP_BRIGHTNESS: u32 = 4353;
pub const ICAP_CONTRAST: u32 = 4355;
pub const ICAP_CUSTHALFTONE: u32 = 4356;
pub const ICAP_EXPOSURETIME: u32 = 4357;
pub const ICAP_FILTER: u32 = 4358;
pub const ICAP_FLASHUSED: u32 = 4359;
pub const ICAP_GAMMA: u32 = 4360;
pub const ICAP_HALFTONES: u32 = 4361;
pub const ICAP_HIGHLIGHT: u32 = 4362;
pub const ICAP_IMAGEFILEFORMAT: u32 = 4364;
pub const ICAP_LAMPSTATE: u32 = 4365;
pub const ICAP_LIGHTSOURCE: u32 = 4366;
pub const ICAP_ORIENTATION: u32 = 4368;
pub const ICAP_PHYSICALWIDTH: u32 = 4369;
pub const ICAP_PHYSICALHEIGHT: u32 = 4370;
pub const ICAP_SHADOW: u32 = 4371;
pub const ICAP_FRAMES: u32 = 4372;
pub const ICAP_XNATIVERESOLUTION: u32 = 4374;
pub const ICAP_YNATIVERESOLUTION: u32 = 4375;
pub const ICAP_XRESOLUTION: u32 = 4376;
pub const ICAP_YRESOLUTION: u32 = 4377;
pub const ICAP_MAXFRAMES: u32 = 4378;
pub const ICAP_TILES: u32 = 4379;
pub const ICAP_BITORDER: u32 = 4380;
pub const ICAP_CCITTKFACTOR: u32 = 4381;
pub const ICAP_LIGHTPATH: u32 = 4382;
pub const ICAP_PIXELFLAVOR: u32 = 4383;
pub const ICAP_PLANARCHUNKY: u32 = 4384;
pub const ICAP_ROTATION: u32 = 4385;
pub const ICAP_SUPPORTEDSIZES: u32 = 4386;
pub const ICAP_THRESHOLD: u32 = 4387;
pub const ICAP_XSCALING: u32 = 4388;
pub const ICAP_YSCALING: u32 = 4389;
pub const ICAP_BITORDERCODES: u32 = 4390;
pub const ICAP_PIXELFLAVORCODES: u32 = 4391;
pub const ICAP_JPEGPIXELTYPE: u32 = 4392;
pub const ICAP_TIMEFILL: u32 = 4394;
pub const ICAP_BITDEPTH: u32 = 4395;
pub const ICAP_BITDEPTHREDUCTION: u32 = 4396;
pub const ICAP_UNDEFINEDIMAGESIZE: u32 = 4397;
pub const ICAP_IMAGEDATASET: u32 = 4398;
pub const ICAP_EXTIMAGEINFO: u32 = 4399;
pub const ICAP_MINIMUMHEIGHT: u32 = 4400;
pub const ICAP_MINIMUMWIDTH: u32 = 4401;
pub const ICAP_FLIPROTATION: u32 = 4406;
pub const ICAP_BARCODEDETECTIONENABLED: u32 = 4407;
pub const ICAP_SUPPORTEDBARCODETYPES: u32 = 4408;
pub const ICAP_BARCODEMAXSEARCHPRIORITIES: u32 = 4409;
pub const ICAP_BARCODESEARCHPRIORITIES: u32 = 4410;
pub const ICAP_BARCODESEARCHMODE: u32 = 4411;
pub const ICAP_BARCODEMAXRETRIES: u32 = 4412;
pub const ICAP_BARCODETIMEOUT: u32 = 4413;
pub const ICAP_ZOOMFACTOR: u32 = 4414;
pub const ICAP_PATCHCODEDETECTIONENABLED: u32 = 4415;
pub const ICAP_SUPPORTEDPATCHCODETYPES: u32 = 4416;
pub const ICAP_PATCHCODEMAXSEARCHPRIORITIES: u32 = 4417;
pub const ICAP_PATCHCODESEARCHPRIORITIES: u32 = 4418;
pub const ICAP_PATCHCODESEARCHMODE: u32 = 4419;
pub const ICAP_PATCHCODEMAXRETRIES: u32 = 4420;
pub const ICAP_PATCHCODETIMEOUT: u32 = 4421;
pub const ICAP_FLASHUSED2: u32 = 4422;
pub const ICAP_IMAGEFILTER: u32 = 4423;
pub const ICAP_NOISEFILTER: u32 = 4424;
pub const ICAP_OVERSCAN: u32 = 4425;
pub const ICAP_AUTOMATICBORDERDETECTION: u32 = 4432;
pub const ICAP_AUTOMATICDESKEW: u32 = 4433;
pub const ICAP_AUTOMATICROTATE: u32 = 4434;
pub const ICAP_JPEGQUALITY: u32 = 4435;
pub const ACAP_AUDIOFILEFORMAT: u32 = 4609;
pub const ACAP_XFERMECH: u32 = 4610;
pub const TWEI_BARCODEX: u32 = 4608;
pub const TWEI_BARCODEY: u32 = 4609;
pub const TWEI_BARCODETEXT: u32 = 4610;
pub const TWEI_BARCODETYPE: u32 = 4611;
pub const TWEI_DESHADETOP: u32 = 4612;
pub const TWEI_DESHADELEFT: u32 = 4613;
pub const TWEI_DESHADEHEIGHT: u32 = 4614;
pub const TWEI_DESHADEWIDTH: u32 = 4615;
pub const TWEI_DESHADESIZE: u32 = 4616;
pub const TWEI_SPECKLESREMOVED: u32 = 4617;
pub const TWEI_HORZLINEXCOORD: u32 = 4618;
pub const TWEI_HORZLINEYCOORD: u32 = 4619;
pub const TWEI_HORZLINELENGTH: u32 = 4620;
pub const TWEI_HORZLINETHICKNESS: u32 = 4621;
pub const TWEI_VERTLINEXCOORD: u32 = 4622;
pub const TWEI_VERTLINEYCOORD: u32 = 4623;
pub const TWEI_VERTLINELENGTH: u32 = 4624;
pub const TWEI_VERTLINETHICKNESS: u32 = 4625;
pub const TWEI_PATCHCODE: u32 = 4626;
pub const TWEI_ENDORSEDTEXT: u32 = 4627;
pub const TWEI_FORMCONFIDENCE: u32 = 4628;
pub const TWEI_FORMTEMPLATEMATCH: u32 = 4629;
pub const TWEI_FORMTEMPLATEPAGEMATCH: u32 = 4630;
pub const TWEI_FORMHORZDOCOFFSET: u32 = 4631;
pub const TWEI_FORMVERTDOCOFFSET: u32 = 4632;
pub const TWEI_BARCODECOUNT: u32 = 4633;
pub const TWEI_BARCODECONFIDENCE: u32 = 4634;
pub const TWEI_BARCODEROTATION: u32 = 4635;
pub const TWEI_BARCODETEXTLENGTH: u32 = 4636;
pub const TWEI_DESHADECOUNT: u32 = 4637;
pub const TWEI_DESHADEBLACKCOUNTOLD: u32 = 4638;
pub const TWEI_DESHADEBLACKCOUNTNEW: u32 = 4639;
pub const TWEI_DESHADEBLACKRLMIN: u32 = 4640;
pub const TWEI_DESHADEBLACKRLMAX: u32 = 4641;
pub const TWEI_DESHADEWHITECOUNTOLD: u32 = 4642;
pub const TWEI_DESHADEWHITECOUNTNEW: u32 = 4643;
pub const TWEI_DESHADEWHITERLMIN: u32 = 4644;
pub const TWEI_DESHADEWHITERLAVE: u32 = 4645;
pub const TWEI_DESHADEWHITERLMAX: u32 = 4646;
pub const TWEI_BLACKSPECKLESREMOVED: u32 = 4647;
pub const TWEI_WHITESPECKLESREMOVED: u32 = 4648;
pub const TWEI_HORZLINECOUNT: u32 = 4649;
pub const TWEI_VERTLINECOUNT: u32 = 4650;
pub const TWEI_DESKEWSTATUS: u32 = 4651;
pub const TWEI_SKEWORIGINALANGLE: u32 = 4652;
pub const TWEI_SKEWFINALANGLE: u32 = 4653;
pub const TWEI_SKEWCONFIDENCE: u32 = 4654;
pub const TWEI_SKEWWINDOWX1: u32 = 4655;
pub const TWEI_SKEWWINDOWY1: u32 = 4656;
pub const TWEI_SKEWWINDOWX2: u32 = 4657;
pub const TWEI_SKEWWINDOWY2: u32 = 4658;
pub const TWEI_SKEWWINDOWX3: u32 = 4659;
pub const TWEI_SKEWWINDOWY3: u32 = 4660;
pub const TWEI_SKEWWINDOWX4: u32 = 4661;
pub const TWEI_SKEWWINDOWY4: u32 = 4662;
pub const TWEI_BOOKNAME: u32 = 4664;
pub const TWEI_CHAPTERNUMBER: u32 = 4665;
pub const TWEI_DOCUMENTNUMBER: u32 = 4666;
pub const TWEI_PAGENUMBER: u32 = 4667;
pub const TWEI_CAMERA: u32 = 4668;
pub const TWEI_FRAMENUMBER: u32 = 4669;
pub const TWEI_FRAME: u32 = 4670;
pub const TWEI_PIXELFLAVOR: u32 = 4671;
pub const TWEJ_NONE: u32 = 0;
pub const TWEJ_MIDSEPARATOR: u32 = 1;
pub const TWEJ_PATCH1: u32 = 2;
pub const TWEJ_PATCH2: u32 = 3;
pub const TWEJ_PATCH3: u32 = 4;
pub const TWEJ_PATCH4: u32 = 5;
pub const TWEJ_PATCH6: u32 = 6;
pub const TWEJ_PATCHT: u32 = 7;
pub const TWDR_GET: u32 = 1;
pub const TWDR_SET: u32 = 2;
pub const TWRC_CUSTOMBASE: u32 = 32768;
pub const TWRC_SUCCESS: u32 = 0;
pub const TWRC_FAILURE: u32 = 1;
pub const TWRC_CHECKSTATUS: u32 = 2;
pub const TWRC_CANCEL: u32 = 3;
pub const TWRC_DSEVENT: u32 = 4;
pub const TWRC_NOTDSEVENT: u32 = 5;
pub const TWRC_XFERDONE: u32 = 6;
pub const TWRC_ENDOFLIST: u32 = 7;
pub const TWRC_INFONOTSUPPORTED: u32 = 8;
pub const TWRC_DATANOTAVAILABLE: u32 = 9;
pub const TWCC_CUSTOMBASE: u32 = 32768;
pub const TWCC_SUCCESS: u32 = 0;
pub const TWCC_BUMMER: u32 = 1;
pub const TWCC_LOWMEMORY: u32 = 2;
pub const TWCC_NODS: u32 = 3;
pub const TWCC_MAXCONNECTIONS: u32 = 4;
pub const TWCC_OPERATIONERROR: u32 = 5;
pub const TWCC_BADCAP: u32 = 6;
pub const TWCC_BADPROTOCOL: u32 = 9;
pub const TWCC_BADVALUE: u32 = 10;
pub const TWCC_SEQERROR: u32 = 11;
pub const TWCC_BADDEST: u32 = 12;
pub const TWCC_CAPUNSUPPORTED: u32 = 13;
pub const TWCC_CAPBADOPERATION: u32 = 14;
pub const TWCC_CAPSEQERROR: u32 = 15;
pub const TWCC_DENIED: u32 = 16;
pub const TWCC_FILEEXISTS: u32 = 17;
pub const TWCC_FILENOTFOUND: u32 = 18;
pub const TWCC_NOTEMPTY: u32 = 19;
pub const TWCC_PAPERJAM: u32 = 20;
pub const TWCC_PAPERDOUBLEFEED: u32 = 21;
pub const TWCC_FILEWRITEERROR: u32 = 22;
pub const TWCC_CHECKDEVICEONLINE: u32 = 23;
pub const TWQC_GET: u32 = 1;
pub const TWQC_SET: u32 = 2;
pub const TWQC_GETDEFAULT: u32 = 4;
pub const TWQC_GETCURRENT: u32 = 8;
pub const TWQC_RESET: u32 = 16;
pub type TW_HANDLE = *mut *mut ::std::os::raw::c_char;
pub type TW_MEMREF = *mut ::std::os::raw::c_char;
pub type TW_STR32 = [::std::os::raw::c_uchar; 34usize];
pub type pTW_STR32 = *mut ::std::os::raw::c_uchar;
pub type TW_STR64 = [::std::os::raw::c_uchar; 66usize];
pub type pTW_STR64 = *mut ::std::os::raw::c_uchar;
pub type TW_STR128 = [::std::os::raw::c_uchar; 130usize];
pub type pTW_STR128 = *mut ::std::os::raw::c_uchar;
pub type TW_STR255 = [::std::os::raw::c_uchar; 256usize];
pub type pTW_STR255 = *mut ::std::os::raw::c_uchar;
pub type TW_INT8 = ::std::os::raw::c_char;
pub type pTW_INT8 = *mut ::std::os::raw::c_char;
pub type TW_INT16 = ::std::os::raw::c_short;
pub type pTW_INT16 = *mut ::std::os::raw::c_short;
pub type TW_INT32 = ::std::os::raw::c_int;
pub type pTW_INT32 = *mut ::std::os::raw::c_int;
pub type TW_UINT8 = ::std::os::raw::c_uchar;
pub type pTW_UINT8 = *mut ::std::os::raw::c_uchar;
pub type TW_UINT16 = ::std::os::raw::c_ushort;
pub type pTW_UINT16 = *mut ::std::os::raw::c_ushort;
pub type TW_UINT32 = ::std::os::raw::c_uint;
pub type pTW_UINT32 = *mut ::std::os::raw::c_uint;
pub type TW_BOOL = ::std::os::raw::c_ushort;
pub type pTW_BOOL = *mut ::std::os::raw::c_ushort;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_FIX32 {
    pub Whole: TW_INT16,
    pub Frac: TW_UINT16,
}
pub type pTW_FIX32 = *mut TW_FIX32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_CIEPOINT {
    pub X: TW_FIX32,
    pub Y: TW_FIX32,
    pub Z: TW_FIX32,
}
pub type pTW_CIEPOINT = *mut TW_CIEPOINT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_DECODEFUNCTION {
    pub StartIn: TW_FIX32,
    pub BreakIn: TW_FIX32,
    pub EndIn: TW_FIX32,
    pub StartOut: TW_FIX32,
    pub BreakOut: TW_FIX32,
    pub EndOut: TW_FIX32,
    pub Gamma: TW_FIX32,
    pub SampleCount: TW_FIX32,
}
pub type pTW_DECODEFUNCTION = *mut TW_DECODEFUNCTION;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_ELEMENT8 {
    pub Index: TW_UINT8,
    pub Channel1: TW_UINT8,
    pub Channel2: TW_UINT8,
    pub Channel3: TW_UINT8,
}
pub type pTW_ELEMENT8 = *mut TW_ELEMENT8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_FRAME {
    pub Left: TW_FIX32,
    pub Top: TW_FIX32,
    pub Right: TW_FIX32,
    pub Bottom: TW_FIX32,
}
pub type pTW_FRAME = *mut TW_FRAME;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_MEMORY {
    pub Flags: TW_UINT32,
    pub Length: TW_UINT32,
    pub TheMem: TW_MEMREF,
}
pub type pTW_MEMORY = *mut TW_MEMORY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_TRANSFORMSTAGE {
    pub Decode: [TW_DECODEFUNCTION; 3usize],
    pub Mix: [[TW_FIX32; 3usize]; 3usize],
}
pub type pTW_TRANSFORMSTAGE = *mut TW_TRANSFORMSTAGE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_VERSION {
    pub MajorNum: TW_UINT16,
    pub MinorNum: TW_UINT16,
    pub Language: TW_UINT16,
    pub Country: TW_UINT16,
    pub Info: TW_STR32,
}
pub type pTW_VERSION = *mut TW_VERSION;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_ARRAY {
    pub ItemType: TW_UINT16,
    pub NumItems: TW_UINT32,
    pub ItemList: [TW_UINT8; 1usize],
}
pub type pTW_ARRAY = *mut TW_ARRAY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_ENUMERATION {
    pub ItemType: TW_UINT16,
    pub NumItems: TW_UINT32,
    pub CurrentIndex: TW_UINT32,
    pub DefaultIndex: TW_UINT32,
    pub ItemList: [TW_UINT8; 1usize],
}
pub type pTW_ENUMERATION = *mut TW_ENUMERATION;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_ONEVALUE {
    pub ItemType: TW_UINT16,
    pub Item: TW_UINT32,
}
pub type pTW_ONEVALUE = *mut TW_ONEVALUE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_RANGE {
    pub ItemType: TW_UINT16,
    pub MinValue: TW_UINT32,
    pub MaxValue: TW_UINT32,
    pub StepSize: TW_UINT32,
    pub DefaultValue: TW_UINT32,
    pub CurrentValue: TW_UINT32,
}
pub type pTW_RANGE = *mut TW_RANGE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_CAPABILITY {
    pub Cap: TW_UINT16,
    pub ConType: TW_UINT16,
    pub hContainer: TW_HANDLE,
}
pub type pTW_CAPABILITY = *mut TW_CAPABILITY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_CIECOLOR {
    pub ColorSpace: TW_UINT16,
    pub LowEndian: TW_INT16,
    pub DeviceDependent: TW_INT16,
    pub VersionNumber: TW_INT32,
    pub StageABC: TW_TRANSFORMSTAGE,
    pub StageLMN: TW_TRANSFORMSTAGE,
    pub WhitePoint: TW_CIEPOINT,
    pub BlackPoint: TW_CIEPOINT,
    pub WhitePaper: TW_CIEPOINT,
    pub BlackInk: TW_CIEPOINT,
    pub Samples: [TW_FIX32; 1usize],
}
pub type pTW_CIECOLOR = *mut TW_CIECOLOR;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_EVENT {
    pub pEvent: TW_MEMREF,
    pub TWMessage: TW_UINT16,
}
pub type pTW_EVENT = *mut TW_EVENT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_GRAYRESPONSE {
    pub Response: [TW_ELEMENT8; 1usize],
}
pub type pTW_GRAYRESPONSE = *mut TW_GRAYRESPONSE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_IDENTITY {
    pub Id: TW_MEMREF,
    pub Version: TW_VERSION,
    pub ProtocolMajor: TW_UINT16,
    pub ProtocolMinor: TW_UINT16,
    pub SupportedGroups: TW_UINT32,
    pub Manufacturer: TW_STR32,
    pub ProductFamily: TW_STR32,
    pub ProductName: TW_STR32,
}
pub type pTW_IDENTITY = *mut TW_IDENTITY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_IMAGEINFO {
    pub XResolution: TW_FIX32,
    pub YResolution: TW_FIX32,
    pub ImageWidth: TW_INT32,
    pub ImageLength: TW_INT32,
    pub SamplesPerPixel: TW_INT16,
    pub BitsPerSample: [TW_INT16; 8usize],
    pub BitsPerPixel: TW_INT16,
    pub Planar: TW_BOOL,
    pub PixelType: TW_INT16,
    pub Compression: TW_UINT16,
}
pub type pTW_IMAGEINFO = *mut TW_IMAGEINFO;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_IMAGELAYOUT {
    pub Frame: TW_FRAME,
    pub DocumentNumber: TW_UINT32,
    pub PageNumber: TW_UINT32,
    pub FrameNumber: TW_UINT32,
}
pub type pTW_IMAGELAYOUT = *mut TW_IMAGELAYOUT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_IMAGEMEMXFER {
    pub Compression: TW_UINT16,
    pub BytesPerRow: TW_UINT32,
    pub Columns: TW_UINT32,
    pub Rows: TW_UINT32,
    pub XOffset: TW_UINT32,
    pub YOffset: TW_UINT32,
    pub BytesWritten: TW_UINT32,
    pub Memory: TW_MEMORY,
}
pub type pTW_IMAGEMEMXFER = *mut TW_IMAGEMEMXFER;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_JPEGCOMPRESSION {
    pub ColorSpace: TW_UINT16,
    pub SubSampling: TW_UINT32,
    pub NumComponents: TW_UINT16,
    pub RestartFrequency: TW_UINT16,
    pub QuantMap: [TW_UINT16; 4usize],
    pub QuantTable: [TW_MEMORY; 4usize],
    pub HuffmanMap: [TW_UINT16; 4usize],
    pub HuffmanDC: [TW_MEMORY; 2usize],
    pub HuffmanAC: [TW_MEMORY; 2usize],
}
pub type pTW_JPEGCOMPRESSION = *mut TW_JPEGCOMPRESSION;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_PALETTE8 {
    pub NumColors: TW_UINT16,
    pub PaletteType: TW_UINT16,
    pub Colors: [TW_ELEMENT8; 256usize],
}
pub type pTW_PALETTE8 = *mut TW_PALETTE8;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct TW_PENDINGXFERS {
    pub __bindgen_anon_1: TW_PENDINGXFERS__bindgen_ty_1,
    pub Count: TW_UINT16,
    pub TW_JOBCONTROL: TW_PENDINGXFERS__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union TW_PENDINGXFERS__bindgen_ty_1 {
    pub EOJ: TW_UINT32,
    pub Reserved: TW_UINT32,
}
pub type pTW_PENDINGXFERS = *mut TW_PENDINGXFERS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_RGBRESPONSE {
    pub Response: [TW_ELEMENT8; 1usize],
}
pub type pTW_RGBRESPONSE = *mut TW_RGBRESPONSE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_SETUPFILEXFER {
    pub FileName: TW_STR255,
    pub Format: TW_UINT16,
    pub VRefNum: TW_INT16,
}
pub type pTW_SETUPFILEXFER = *mut TW_SETUPFILEXFER;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_SETUPFILEXFER2 {
    pub FileName: TW_MEMREF,
    pub FileNameType: TW_UINT16,
    pub Format: TW_UINT16,
    pub VRefNum: TW_INT16,
    pub ParID: TW_UINT32,
}
pub type pTW_SETUPFILEXFER2 = *mut TW_SETUPFILEXFER2;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_SETUPMEMXFER {
    pub MinBufSize: TW_UINT32,
    pub MaxBufSize: TW_UINT32,
    pub Preferred: TW_UINT32,
}
pub type pTW_SETUPMEMXFER = *mut TW_SETUPMEMXFER;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_STATUS {
    pub ConditionCode: TW_UINT16,
    pub Reserved: TW_UINT16,
}
pub type pTW_STATUS = *mut TW_STATUS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_USERINTERFACE {
    pub ShowUI: TW_BOOL,
    pub ModalUI: TW_BOOL,
    pub hParent: TW_HANDLE,
}
pub type pTW_USERINTERFACE = *mut TW_USERINTERFACE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_TWUNKIDENTITY {
    pub identity: TW_IDENTITY,
    pub dsPath: TW_STR255,
}
pub type pTW_TWUNKIDENTITY = *mut TW_TWUNKIDENTITY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_TWUNKDSENTRYPARAMS {
    pub destFlag: TW_INT8,
    pub dest: TW_IDENTITY,
    pub dataGroup: TW_INT32,
    pub dataArgType: TW_INT16,
    pub message: TW_INT16,
    pub pDataSize: TW_INT32,
}
pub type pTW_TWUNKDSENTRYPARAMS = *mut TW_TWUNKDSENTRYPARAMS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_TWUNKDSENTRYRETURN {
    pub returnCode: TW_UINT16,
    pub conditionCode: TW_UINT16,
    pub pDataSize: TW_INT32,
}
pub type pTW_TWUNKDSENTRYRETURN = *mut TW_TWUNKDSENTRYRETURN;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_CAPEXT {
    pub Cap: TW_UINT16,
    pub Properties: TW_UINT16,
}
pub type pTW_CAPEXT = *mut TW_CAPEXT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_CUSTOMDSDATA {
    pub InfoLength: TW_UINT32,
    pub hData: TW_HANDLE,
}
pub type pTW_CUSTOMDSDATA = *mut TW_CUSTOMDSDATA;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_INFO {
    pub InfoID: TW_UINT16,
    pub ItemType: TW_UINT16,
    pub NumItems: TW_UINT16,
    pub CondCode: TW_UINT16,
    pub Item: TW_UINT32,
}
pub type pTW_INFO = *mut TW_INFO;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_EXTIMAGEINFO {
    pub NumInfos: TW_UINT32,
    pub Info: [TW_INFO; 1usize],
}
pub type pTW_EXTIMAGEINFO = *mut TW_EXTIMAGEINFO;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_AUDIOINFO {
    pub Name: TW_STR255,
    pub Reserved: TW_UINT32,
}
pub type pTW_AUDIOINFO = *mut TW_AUDIOINFO;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_DEVICEEVENT {
    pub Event: TW_UINT32,
    pub DeviceName: TW_STR255,
    pub BatteryMinutes: TW_UINT32,
    pub BatteryPercentage: TW_INT16,
    pub PowerSupply: TW_INT32,
    pub XResolution: TW_FIX32,
    pub YResolution: TW_FIX32,
    pub FlashUsed2: TW_UINT32,
    pub AutomaticCapture: TW_UINT32,
    pub TimeBeforeFirstCapture: TW_UINT32,
    pub TimeBetweenCaptures: TW_UINT32,
}
pub type pTW_DEVICEEVENT = *mut TW_DEVICEEVENT;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_FILESYSTEM {
    pub InputName: TW_STR255,
    pub OutputName: TW_STR255,
    pub Context: TW_MEMREF,
    pub Recursive: ::std::os::raw::c_int,
    pub FileType: TW_INT32,
    pub Size: TW_UINT32,
    pub CreateTimeDate: TW_STR32,
    pub ModifiedTimeDate: TW_STR32,
    pub FreeSpace: TW_UINT32,
    pub NewImageSize: TW_INT32,
    pub NumberOfFiles: TW_UINT32,
    pub NumberOfSnippets: TW_UINT32,
    pub DeviceGroupMask: TW_UINT32,
    pub Reserved: [::std::os::raw::c_char; 508usize],
}
pub type pTW_FILESYSTEM = *mut TW_FILESYSTEM;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_PASSTHRU {
    pub pCommand: TW_MEMREF,
    pub CommandBytes: TW_UINT32,
    pub Direction: TW_INT32,
    pub pData: TW_MEMREF,
    pub DataBytes: TW_UINT32,
    pub DataBytesXfered: TW_UINT32,
}
pub type pTW_PASSTHRU = *mut TW_PASSTHRU;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_SETUPAUDIOFILEXFER {
    pub FileName: TW_STR255,
    pub Format: TW_UINT16,
    pub VRefNum: TW_INT16,
}
pub type pTW_SETUPAUDIOFILEXFER = *mut TW_SETUPAUDIOFILEXFER;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TW_CALLBACK {
    pub CallBackProc: TW_MEMREF,
    pub RefCon: TW_MEMREF,
    pub Message: TW_INT16,
}
pub type pTW_CALLBACK = *mut TW_CALLBACK;
extern "C" {
    pub fn DSM_Entry(
        pOrigin: pTW_IDENTITY,
        pDest: pTW_IDENTITY,
        DG: TW_UINT32,
        DAT: TW_UINT16,
        MSG: TW_UINT16,
        pData: TW_MEMREF,
    ) -> TW_UINT16;
}
pub type DSMENTRYPROC = ::std::option::Option<
    unsafe extern "C" fn(
        pOrigin: pTW_IDENTITY,
        pDest: pTW_IDENTITY,
        DG: TW_UINT32,
        DAT: TW_UINT16,
        MSG: TW_UINT16,
        pData: TW_MEMREF,
    ) -> TW_UINT16,
>;
extern "C" {
    pub fn DS_Entry(
        pOrigin: pTW_IDENTITY,
        DG: TW_UINT32,
        DAT: TW_UINT16,
        MSG: TW_UINT16,
        pData: TW_MEMREF,
    ) -> TW_UINT16;
}
pub type DSENTRYPROC = ::std::option::Option<
    unsafe extern "C" fn(
        pOrigin: pTW_IDENTITY,
        DG: TW_UINT32,
        DAT: TW_UINT16,
        MSG: TW_UINT16,
        pData: TW_MEMREF,
    ) -> TW_UINT16,
>;
